insert into artist values (1,'Скриптонит');
insert into artist values (2,'Николай Басков');
insert into artist values (3,'Jony');
insert into artist values (4,'Adele');
insert into artist values (5,'Баста');
insert into artist values (6,'Ярослав Евдокимов');
insert into artist values (7,'Лариса Долина');
insert into artist values (8,'Клава Кока');

insert into genre values (1,'Рэп');
insert into genre values (2,'Поп-музыка');
insert into genre values (3,'Джаз');
insert into genre values (4,'Рок');
insert into genre values (5,'Опера');

insert into album values (1,'Голос улиц', '2015-08-20');
insert into album values (2,'В джазе только девушки', '2007-02-11');
insert into album values (3,'Кровавая гитара', '2017-04-10');
insert into album values (4,'Я-тенор', '2000-10-11');
insert into album values (5,'16', '2005-05-05');
insert into album values (6,'Фантазер', '1981-07-19');
insert into album values (7,'Хочешь?', '2020-12-19');
insert into album values (8,'Hello!', '2018-10-25');

insert into song values (1, 1, 'Моя игра', '2015-09-12');
insert into song values (2, 2, 'Moon River', '2006-10-13');
insert into song values (3, 7, 'Хочешь', '2019-05-23');
insert into song values (4, 5, 'Rolling in the deep', '2004-09-09');
insert into song values (5, 4, 'Barcelona', '2000-08-08');
insert into song values (6, 5, 'Hello', '2018-12-21');
insert into song values (7, 3, 'Рок-стар', '2016-11-30');
insert into song values (8, 8, 'Комета', '2017-08-09');
insert into song values (9, 6, 'Музыка нас связала', '1980-07-24');
insert into song values (10, 8, 'Пустой стакан', '2018-01-01');
insert into song values (11, 8, 'Белое платье', '2018-09-12');
insert into song values (12, 4, 'Strangers in the night', '1999-03-24');
insert into song values (13, 3, 'Группа крови cover', '2017-11-22');
insert into song values (14, 1, 'Москва любит', '2015-09-22');
insert into song values (15, 6, 'Колодец', '1980-10-10');

insert into collection values (1,'Дискотека 90-х', '2010-05-04');
insert into collection values (2,'На иностранном', '2018-10-10');
insert into collection values (3,'Гитарой об пол', '2017-09-12');
insert into collection values (4,'Пацанский рэп', '2020-06-30');
insert into collection values (5,'Современное', '2021-11-12');
insert into collection values (6,'Погрустить', '2019-09-10');
insert into collection values (7,'Повеселиться', '2020-12-12');
insert into collection values (8,'Споем вместе', '2017-05-03');

insert into genreartist values (1,1);
insert into genreartist values (2,1);
insert into genreartist values (2,2);
insert into genreartist values (5,2);
insert into genreartist values (2,3);
insert into genreartist values (4,3);
insert into genreartist values (2,4);
insert into genreartist values (1,5);
insert into genreartist values (2,5);
insert into genreartist values (2,6);
insert into genreartist values (2,7);
insert into genreartist values (3,7);
insert into genreartist values (1,8);
insert into genreartist values (2,8);

insert into collectionsong values (1,5);
insert into collectionsong values (1,9);
insert into collectionsong values (1,12);
insert into collectionsong values (1,15);
insert into collectionsong values (2,2);
insert into collectionsong values (2,4);
insert into collectionsong values (2,5);
insert into collectionsong values (2,6);
insert into collectionsong values (2,12);
insert into collectionsong values (3,4);
insert into collectionsong values (3,7);
insert into collectionsong values (3,13);
insert into collectionsong values (4,1);
insert into collectionsong values (4,6);
insert into collectionsong values (4,10);
insert into collectionsong values (4,14);
insert into collectionsong values (5,1);
insert into collectionsong values (5,3);
insert into collectionsong values (5,6);
insert into collectionsong values (5,10);
insert into collectionsong values (5,11);
insert into collectionsong values (6,3);
insert into collectionsong values (6,10);
insert into collectionsong values (6,11);
insert into collectionsong values (7,9);
insert into collectionsong values (7,13);
insert into collectionsong values (7,14);
insert into collectionsong values (8,1);
insert into collectionsong values (8,4);
insert into collectionsong values (8,15);

insert into albumartist values (1,1);
insert into albumartist values (4,2);
insert into albumartist values (3,3);
insert into albumartist values (8,3);
insert into albumartist values (5,4);
insert into albumartist values (1,5);
insert into albumartist values (6,6);
insert into albumartist values (7,8);
insert into albumartist values (2,7);

alter table song add column song_time numeric(3,2);
update song set song_time = 3.43 where id = 1;
update song set song_time = 2.56 where id = 2;
update song set song_time = 3.10 where id = 3;
update song set song_time = 4.12 where id = 4;
update song set song_time = 5.01 where id = 5;
update song set song_time = 3.12 where id = 6;
update song set song_time = 2.59 where id = 7;
update song set song_time = 4.40 where id = 8;
update song set song_time = 3.29 where id = 9;
update song set song_time = 3.30 where id = 10;
update song set song_time = 4.01 where id = 11;
update song set song_time = 4.11 where id = 12;
update song set song_time = 2.59 where id = 13;
update song set song_time = 5.00 where id = 14;
update song set song_time = 3.45 where id = 15;